# Generated by Django 4.2.16 on 2024-10-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRawJunction',
            fields=[
                ('junctionid', models.IntegerField(primary_key=True, serialize=False)),
                ('rawitemid', models.IntegerField(blank=True, null=True)),
                ('itemid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu_raw_junction',
            },
        ),
        migrations.CreateModel(
            name='RawInventory',
            fields=[
                ('rawitemid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('min', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_inventory',
            },
        ),
    ]
