# Generated by Django 4.2.16 on 2024-11-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInfo',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
